### ISSUE TITLE
IcomoonIkonHandler oes not define or inherit an implementation of the resolved method 'abstract java.net.URL getFontResource()

### ISSUE THREAD

**Issue by georgemoralis** [kordamp/ikonli#129]
got this after updating to 12.1.0

Caused by: java.lang.AbstractMethodError: Receiver class org.kordamp.ikonli.icomoon.IcomoonIkonHandler does not define or inherit an implementation of the resolved method 'abstract java.net.URL getFontResource()' of interface org.kordamp.ikonli.IkonHandler.
	at org.kordamp.ikonli.javafx.IkonResolver.<clinit>(IkonResolver.java:42)
	at org.kordamp.ikonli.javafx.FontIcon.setIconLiteral(FontIcon.java:232)

**Comment by georgemoralis** [comment]
the fxml part

      <FontIcon iconColor="#0044ff" iconLiteral="mdi-account" iconSize="128" wrappingWidth="128.0" GridPane.columnIndex="1" GridPane.rowIndex="2">
         <GridPane.margin>
            <Insets left="35.0" />
         </GridPane.margin>
      </FontIcon>

**Comment by georgemoralis** [comment]
And this when i load it from scenebuilder

Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.kordamp.ikonli.javafx.IkonResolver
	at org.kordamp.ikonli.javafx.FontIcon.setIconLiteral(FontIcon.java:232)
	... 71 more

**Comment by georgemoralis** [comment]
hmm sorry i had an old 11.5.0 font lib loaded somewhere. Now it works perfectly :)
